---
    initial_site: "http://www.scpwiki.com/"
    links_file: "found_links.yaml"
    blacklisting_regex:
        - r"^\/(theme|system|random):"
        - r"^\/(forum)[/:]"
        - r"^\/top-rated-(pages-this-month|goi-formats)"
        - r"^\/lowest-rated-pages"
        - r"^\/april-fools-(2020|2014)"
        - r"^\/most-recently-edited"
        - r"^\/(exquisite-corpse|canon-renaissance)-contest"
        - r"^\/(scp-artwork-hub|audio-adaptations|desk-of-junior-designer-s-yvonne|seminars-hub)"
        - r"^\/(how-to-write-an-scp|cliches-and-you-an-educational-film|user-curated-lists|tag-search)"
        - r"^\/(authors-pages|flawed-profile|meet-the-staff)"
        - r"^\/guide-(hub|for-newbies)"
        - r"^\/scp-914-experiment-log-guidelines"
        - r"^\/(about-the-scp-foundation|third-party-cookies|contact-staff)"
        - r"^\/incident-reports-eye-witness-interviews-and-personal-logs"
        - r"^\/(new-pages-feed|young-and-under-30)"
        - r"-(personnel-file|author-page)$"
        - r"^\/dr-rogets-file"
        - r"^\/news"
        - r"^\/(deletions|chat|licensing)-guide"
        - r"^\/(faq|links|usertools|object-class-podcast|site-rules|contribute|sandbox|scp-achievement-badges)"
        - r"^\/(criticism|image-use|donations)-policy"
        - r"#.+$"
        - r"^\/archived-(news|scps)"
        - r"archive(-i+)?$"